name: build_context_provider
description: A package that allows you to run functions that require BuildContext outside of Flutter widgets.
version: 1.1.0
repository: https://github.com/Undeadlol1/build_context_provider

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
